version: '3.2'
services:
    nereid:
        image: ioexcept/nereid:1.1
        container_name: nereid
        environment:
            REDIS_SERVER: ${REDIS_SERVER}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_AUTH: ${REDIS_AUTH}
        ports:
            - 8080:8080
